### ISSUE TITLE
auto update wordpress

### ISSUE THREAD

**Issue by unmanagedtn** [stephdl/dev#5] opened 2018-05-19 02:49 UTC
auto update setting is set and not working its asking for ftp password and I need to update to latest

**Comment by stephdl** [comment] 2018-05-19 07:03
In a short message you can't

see /usr/share/wordpress/wp-config.php
```
/**
 * See http://make.wordpress.org/core/2013/10/25/the-definitive-guide-to-disabling-auto-updates-in-wordpress-3-7
 */

/* Disable all file change, as RPM base installation are read-only */
define('DISALLOW_FILE_MODS', false);

/* Disable automatic updater, in case you want to allow
   above FILE_MODS for plugins, themes, ... */
define('AUTOMATIC_UPDATER_DISABLED', true);

/* Core update is always disabled, WP_AUTO_UPDATE_CORE value is ignore */

```

I updated the documentation in the wiki, please give  an eye and reopen if something is wrong for you.

Only theme and translation can be updated by the admin page

closing as not a bug

**Closed as completed by stephdl** 2018-05-19 07:03 UTC

**Comment by unmanagedtn** [comment] 2018-05-19 14:04
so whats the right way to do it with your plugin as not to break neth and
wp? it is not working via FTP also something about permission errors... not sure what its talking about...
