### ISSUE TITLE
Dolibarr (new install) hangs after Webinstallation - user (admin) exists...

### ISSUE THREAD

**Issue by Andy-Wismer** [stephdl/dev#19] opened 2021-10-29 11:41 UTC
Salut Stéphane

I've installed a new "hosted" NethServer at Hetzner in Germany. This Server is a VM under Proxmox with a quad core CPU, 8 GB RAM and 200 GB Disks and a dedicated IP. The server only uses internal IPs, an OPNsense firewall passes external IPs using 1:1 NAT.

Wanting to be able to use Dolibarr, I tried installing it.
The Web installer always hangs toward the end of the installation, when it asks you to set an "admin" user and password. the user admin is grey, can't be changed. Using the AD admin password (or any other) fails, as the Webinstaller reports "user already exists".

I've removed both packages, the configuration and any other files I've found and reinstalled, with exactly the same effect: "user already exists"...

What can be done?

Thanks iA!

Andy

**Comment by stephdl** [comment] 2021-10-29 14:53
what is the account provider do you use : Samba AD or openldap or none ?

> The Web installer always hangs toward the end of the installation, when it asks you to set an "admin" user and password. the user admin is grey, can't be changed. Using the AD admin password (or any other) fails, as the Webinstaller reports "user already exists".


Normally you should never see the web installer

> I've removed both packages, the configuration and any other files I've found and reinstalled, with exactly the same effect: "user already exists"...

the user already exists in the mysql database, you could drop it

**Comment by Andy-Wismer** [comment] 2021-10-29 15:47
Hi

I'm using SMB/AD - with LetsEncrypt ssl certs...

**Comment by Andy-Wismer** [comment] 2021-10-29 22:07
Hi

I have the dolibarr database open in PHPMyAdmin, but I can't find a table containing users...
Any tips?

**Comment by stephdl** [comment] 2021-10-30 13:19
> Any tips?

I am sorry I cannot reproduce, I took a VM with a samba container installed locally, does it is your case ?

The installation is fine, maybe you best chance to understand what it occured is to read the messages log, during the installation everything is logged


To install : `yum install nethserver-dolibarr --enablerepo=stephdl-dolibarr -y`


If it is a new install you can try

```
yum remove nethserver-dolibarr
rm -rf /usr/share/dolibarr
config delete dolibarr
mysql
drop database dolibarr;
yum install nethserver-dolibarr --enablerepo=stephdl-dolibarr
```


you should never see the web installer when you go to https://IP/dolibarr

**Comment by Andy-Wismer** [comment] 2021-12-29 22:42
Hi

This "issue" can be closed - did not manifest itself after reinstall... :-)

Merci!

**Comment by stephdl** [comment] 2021-12-30 14:02
set closed as requested above

**Closed as completed by stephdl** 2021-12-30 14:02 UTC
